name: janelia2020
channels:
  - conda-forge
dependencies:
  - python=3.8
  - hypothesis
  - jupyter
  - jupyterlab
  - numpy
  - pytest
  - seaborn
  - scipy
  - scikit-learn
  - scikit-image
  - scikit-optimize
  - pip
  - pytables
  - pip:
      - jax
      - jaxlib