name: janelia2020
channels:
  - conda-forge
dependencies:
  - python
  - altair
  - black
  - hypothesis
  - isort
  - jupyter
  - jupyterlab
  - jupytext
  - numpy
  - pytest
  - seaborn
  - scipy
  - scikit-learn
  - scikit-image
  - scikit-optimize
  - papermill
  - pip
  - pytables
  - pip:
      - jax
      - jaxlib
